export const REGISTER_LOADING = 'REGISTER_LOADING';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RELOAD_ERROR = 'RELOAD_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const EXPIRED_TOKEN = 'EXPIRED_TOKEN';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_LOADING = 'GET_CONTACTS_LOADING';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const CREATE_CONTACTS_LOADING = 'CREATE_CONTACTS_LOADING';
export const CREATE_CONTACTS_FAIL = 'CREATE_CONTACTS_FAIL';
